export default {
  SEARCH_RESULTS: "SEARCH_RESULTS",
  VIEW_BOOK: "VIEW_BOOK",
  LOADING: "LOADING",
  SAVE_BOOK: "SAVE_BOOK",
  GET_SAVED_BOOKS: "GET_SAVED_BOOKS",
  DELETE_BOOK: "DELETE_BOOK",
  UPDATE_SEARCH_RESULTS: "UPDATE_SEARCH_RESULTS",
  VIEW_DETAILS: "VIEW_DETAILS",
};
